services:
  - type: web
    name: iusnauta-backend
    env: python
    region: ohio
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false